In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])
a_r = a.reshape(3,3)

![title](img/nmp1.jpg)

### Способы формирования массивов

In [88]:
lst = [1,2,3,4,5,6,7,8,9]
lst_3_2 = [[1,2],[3,4],[5,6]]
lst_3_3_2 = [[[1,2],[3,4],[5,6]]]

a_1 = np.array(lst, dtype = 'float64')
a_str = np.array(lst, dtype = 'str_') # преобразуем в строки
a_2 = np.array(lst_3_2)
a_3 = np.array(lst_3_3_2)

np.zeros(10)
np.empty(10)
np.eye(3,3)
np.full((3,3,3),'hello')

np.mat('1 2 3 4')
np.diag([1,2,3])
np.tri(3,3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

### Частые

In [79]:
a_4 = a_3.copy()
np.r_[1:9]
np.arange(0,np.pi,0.1)
np.cos(np.arange(0,np.pi,0.1))
np.linspace(1,5,10) # равномерное разделение
np.logspace(2,5,4) # 10 в степени нач., 10 в степени конечной, количество
np.geomspace(1,20,3) # начальное, конечное, количество. Геометрическая прогрессия
np.fromstring('1 2 3 4 5 6', dtype ='int16', sep = ' ')

array([1, 2, 3, 4, 5, 6], dtype=int16)

### Свойства и представления. 

Все представления ссылаются на первоначальные данные и при их изменений другие представления также поменяются
Изменения формы, срезы - создают новые представления.
Математические операции создают уже новые массивы

In [138]:
a_1.dtype
a_1.size
a_1.ndim 
a_3.shape
a_3.shape = 6
a_3.reshape(1,3,2)
a.resize(3,3,refcheck = False) # отбрасывает лишние элементы чтобы выполнить форму
a= np.arange(9).reshape(3,3)
a.T
a.shape = -1,9 # добавляем нулевую ось
np.expand_dims(a,axis =0) # добавляем нулевую ось

a= np.arange(32).reshape(8,2,2)
b = np.expand_dims(a,axis =0)
b= np.append(b,b,axis =0)
b = np.delete(b,0,axis =0)
np.squeeze(b) # удаляет оси где 1 значение

### Объединение и разделение

In [230]:
a = np.array(np.arange(1,5).reshape(2,2))
b = np.array(np.arange(5,9).reshape(2,2))

In [ ]:
np.hstack([a,b]) # объединение по горизонтали
np.append(a,b,axis =1)

np.vstack([a,b]) # объединение по вертикали
np.append(a,b,axis =0)

a = np.array(np.arange(1,5))
b = np.array(np.arange(5,9))

np.column_stack([a,b])  # объединение колонок 

np.row_stack([a,b]) # обхъединение строк


a = np.arange(1,19).reshape(3,3,2)
b = np.arange(19,37).reshape(3,3,2)

np.concatenate([a,b],axis=0) # Размерность 6,3,2
np.r_[a,b]

np.concatenate([a,b],axis=1) # Размерность 3,6,2

np.concatenate([a,b],axis=2) # Размерность 3,3,4
np.c_[a,b]

a = np.arange(1,11)
np.hsplit(a,2)
np.vsplit(a.reshape(10,1),2)

### Матричные и векторные вычисления

Матричное умножение

In [22]:
A = np.arange(9).reshape(3,3)
B = np.arange(9).reshape(3,3)
np.matmul(A,B) # матричное умножение. Размерности матриц должны совпадать
A@B

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

Внутреннее и внешнее умножение векторрв

In [46]:
a =np.array([1,2,3,4]).reshape(2,2)
b =np.array([4,3,2,1]).reshape(2,2)

np.inner(a,b) #внутреннее умножение, разворачивает матрицу для корректного умножения

np.outer(a,b)#внешнее умножение

array([[ 4,  3,  2,  1],
       [ 8,  6,  4,  2],
       [12,  9,  6,  3],
       [16, 12,  8,  4]])

In [74]:
a =np.array([1,2,3])
b =np.array([[4,3,2],[1,1,1],[1,1,1]])

In [75]:
np.inner(a,b)
np.outer(a,b)

array([[ 4,  3,  2,  1,  1,  1,  1,  1,  1],
       [ 8,  6,  4,  2,  2,  2,  2,  2,  2],
       [12,  9,  6,  3,  3,  3,  3,  3,  3]])

In [79]:
a+b

array([[5, 5, 5],
       [2, 3, 4],
       [2, 3, 4]])