In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])
a_r = a.reshape(3,3)

![title](img/nmp1.jpg)

### Способы формирования массивов

In [3]:
lst = [1,2,3,4,5,6,7,8,9]
lst_3_2 = [[1,2],[3,4],[5,6]]
lst_3_3_2 = [[[1,2],[3,4],[5,6]]]

a_1 = np.array(lst, dtype = 'float64')
a_str = np.array(lst, dtype = 'str_') # преобразуем в строки
a_2 = np.array(lst_3_2)
a_3 = np.array(lst_3_3_2)

np.zeros(10)
np.empty(10)
np.eye(3,3)
np.full((3,3,3),'hello')

np.mat('1 2 3 4')
np.diag([1,2,3])
np.tri(3,3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

### Частые

In [79]:
a_4 = a_3.copy()
np.r_[1:9]
np.arange(0,np.pi,0.1) # (start, stop, step)
np.cos(np.arange(0,np.pi,0.1))
np.linspace(1,5,10) # равномерное разделение (start, step, num)
np.logspace(2,5,4) # 10 в степени нач., 10 в степени конечной, количество
np.geomspace(1,20,3) # начальное, конечное, количество. Геометрическая прогрессия
np.fromstring('1 2 3 4 5 6', dtype ='int16', sep = ' ')
.cumsum() # накопительно

array([1, 2, 3, 4, 5, 6], dtype=int16)

### Свойства и представления. 

Все представления ссылаются на первоначальные данные и при их изменений другие представления также поменяются
Изменения формы, срезы - создают новые представления.
Математические операции создают уже новые массивы

In [138]:
a_1.dtype
a_1.size
a_1.ndim 
a_3.shape
a_3.shape = 6
a_3.reshape(1,3,2)
a.resize(3,3,refcheck = False) # отбрасывает лишние элементы чтобы выполнить форму
a= np.arange(9).reshape(3,3)
a.T
a.shape = -1,9 # добавляем нулевую ось
np.expand_dims(a,axis =0) # добавляем нулевую ось

a= np.arange(32).reshape(8,2,2)
b = np.expand_dims(a,axis =0)
b= np.append(b,b,axis =0)
b = np.delete(b,0,axis =0)
np.squeeze(b) # удаляет оси где 1 значение

### Объединение и разделение

In [230]:
a = np.array(np.arange(1,5).reshape(2,2))
b = np.array(np.arange(5,9).reshape(2,2))

In [ ]:
np.hstack([a,b]) # объединение по горизонтали
np.append(a,b,axis =1)

np.vstack([a,b]) # объединение по вертикали
np.append(a,b,axis =0)

a = np.array(np.arange(1,5))
b = np.array(np.arange(5,9))

np.column_stack([a,b])  # объединение колонок 

np.row_stack([a,b]) # обхъединение строк


a = np.arange(1,19).reshape(3,3,2)
b = np.arange(19,37).reshape(3,3,2)

np.concatenate([a,b],axis=0) # Размерность 6,3,2
np.r_[a,b]

np.concatenate([a,b],axis=1) # Размерность 3,6,2

np.concatenate([a,b],axis=2) # Размерность 3,3,4
np.c_[a,b]

a = np.arange(1,11)
np.hsplit(a,2)
np.vsplit(a.reshape(10,1),2)

### Матричные и векторные вычисления

Матричное умножение

In [22]:
A = np.arange(9).reshape(3,3)
B = np.arange(9).reshape(3,3)
np.matmul(A,B) # матричное умножение. Размерности матриц должны совпадать
A@B

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

Внутреннее и внешнее умножение векторрв

In [46]:
a =np.array([1,2,3,4]).reshape(2,2)
b =np.array([4,3,2,1]).reshape(2,2)

np.inner(a,b) #внутреннее умножение, разворачивает матрицу для корректного умножения

np.outer(a,b)#внешнее умножение

array([[ 4,  3,  2,  1],
       [ 8,  6,  4,  2],
       [12,  9,  6,  3],
       [16, 12,  8,  4]])

In [74]:
a =np.array([1,2,3])
b =np.array([[4,3,2],[1,1,1],[1,1,1]])

In [75]:
np.inner(a,b)
np.outer(a,b)

array([[ 4,  3,  2,  1,  1,  1,  1,  1,  1],
       [ 8,  6,  4,  2,  2,  2,  2,  2,  2],
       [12,  9,  6,  3,  3,  3,  3,  3,  3]])

### Рандомы

In [15]:
a = np.random.choice(1000,size=100,replace = False) # выбор из 1000
b = [1,2,3,4]
c = np.random.choice(b,size=(3,2)) # выбор из списка b
d = np.random.randint(100,size=(3,2)) # выбор из 100
e = np.random.random(10) # выбор от 0 до 1, 10 раз
a1,b1,c1 = np.random.normal(2, 3, size=(3, 100))  # выбор  мат.ожидание -2, отклонение -3 

### Маски Where Select

In [21]:
tall = np.random.normal(176, 10, 1000) 

In [25]:
tall[(tall>=170)&(tall<=180)] #фильтр по условию
np.where((tall>=170)&(tall<=180)) # получить не значения а ИНДЕКСЫ

array([186.58374582, 184.4497008 , 160.12606599, 179.91420828,
       171.35535935, 162.69021026, 179.54249308, 186.91368742,
       181.94493602, 177.44017943, 162.99170202, 187.93699131,
       171.60621602, 184.78201029, 169.12800201, 168.48196986,
       166.63923528, 168.92051217, 176.28970172, 163.50332386,
       177.25191594, 173.94337686, 169.3052791 , 176.46397619,
       171.63678678, 169.40760819, 171.89564648, 174.80548917,
       175.25175916, 188.83071959, 171.44025269, 170.28336112,
       176.38187425, 179.5353947 , 175.03183877, 176.45069286,
       163.90816638, 181.74486002, 180.52912692, 161.69592471,
       183.81675342, 177.27716453, 173.63837159, 167.81556568,
       174.12877159, 189.84432242, 178.21446722, 168.53501071,
       176.48989283, 181.70041437, 179.96810321, 176.91686257,
       175.18348186, 163.54088179, 161.18784773, 169.23677883,
       171.04401122, 180.3856361 , 187.05525971, 180.9893474 ,
       160.05771783, 168.34608786, 173.49274046, 173.66

In [32]:
np.where((tall>=170)&(tall<=180),"средний рост", "не средний рост") # фильтр + 

array(['не средний рост', 'не средний рост', 'не средний рост',
       'не средний рост', 'средний рост', 'средний рост',
       'не средний рост', 'средний рост', 'не средний рост',
       'не средний рост', 'не средний рост', 'не средний рост',
       'не средний рост', 'средний рост', 'не средний рост',
       'не средний рост', 'не средний рост', 'средний рост',
       'не средний рост', 'не средний рост', 'не средний рост',
       'не средний рост', 'не средний рост', 'не средний рост',
       'средний рост', 'не средний рост', 'средний рост', 'средний рост',
       'не средний рост', 'средний рост', 'средний рост',
       'не средний рост', 'средний рост', 'средний рост', 'средний рост',
       'не средний рост', 'средний рост', 'средний рост', 'средний рост',
       'не средний рост', 'средний рост', 'средний рост', 'средний рост',
       'не средний рост', 'не средний рост', 'не средний рост',
       'не средний рост', 'не средний рост', 'не средний рост',
       'не средний ро

In [33]:
condition = [tall<170,(tall>=170)&(tall<=180),tall>180]
choise = ['низкие','средние','высокие']
np.select(condition,choise) # фильтр ++

array(['высокие', 'высокие', 'высокие', 'низкие', 'средние', 'средние',
       'низкие', 'средние', 'высокие', 'высокие', 'низкие', 'высокие',
       'высокие', 'средние', 'низкие', 'высокие', 'низкие', 'средние',
       'высокие', 'высокие', 'низкие', 'низкие', 'низкие', 'низкие',
       'средние', 'низкие', 'средние', 'средние', 'низкие', 'средние',
       'средние', 'низкие', 'средние', 'средние', 'средние', 'высокие',
       'средние', 'средние', 'средние', 'высокие', 'средние', 'средние',
       'средние', 'низкие', 'высокие', 'высокие', 'низкие', 'высокие',
       'высокие', 'высокие', 'средние', 'средние', 'высокие', 'низкие',
       'средние', 'высокие', 'средние', 'низкие', 'средние', 'высокие',
       'низкие', 'высокие', 'средние', 'средние', 'низкие', 'средние',
       'низкие', 'низкие', 'низкие', 'средние', 'низкие', 'высокие',
       'высокие', 'высокие', 'низкие', 'низкие', 'средние', 'высокие',
       'средние', 'высокие', 'высокие', 'средние', 'низкие', 'низкие',
    